### ISSUE TITLE
Unable to parse filename %FILENAME% due to delimiter "-.-" missing`

### ISSUE THREAD

**Issue by jje0008** [Banh-Canh/Manga-Tagger#20]
Running latest images of Manga-Tagger and Manga-Tagger-DB and upon first trial I get the message below from the logs:

`2022-02-15T03:23:02.937007684Z [cont-init.d] 99-custom-files: exited 0.`
`2022-02-15T03:23:02.937508911Z [cont-init.d] done.`
`2022-02-15T03:23:02.938129890Z [services.d] starting services`
`2022-02-15T03:23:02.945719191Z [services.d] done.`
`2022-02-15T03:23:03.932360242Z 2022-02-14 22:23:03,932 | MainThread 140282712611656 | MangaTaggerLib.database.Database | INFO - Establishing database connection...`
`2022-02-15T03:23:05.455800914Z 2022-02-14 22:23:05,455 | MainThread 140282712611656 | MangaTaggerLib.database.Database | INFO - Database connection established!`
`2022-02-15T03:23:05.456758260Z 2022-02-14 22:23:05,456 | MainThread 140282712611656 | MangaTaggerLib.utils.AppSettings | INFO - Download directory has been set as "/downloads"`
`2022-02-15T03:23:05.457822726Z 2022-02-14 22:23:05,457 | MainThread 140282712611656 | MangaTaggerLib.utils.AppSettings | INFO - Image directory "/config/cover" does not exist; creating now.`
`2022-02-15T03:23:05.458855130Z 2022-02-14 22:23:05,458 | MainThread 140282712611656 | MangaTaggerLib.utils.AppSettings | INFO - Data directory "None" does not exist; creating now.`
`2022-02-15T03:23:05.459871527Z 2022-02-14 22:23:05,459 | MainThread 140282712611656 | MangaTaggerLib.database.ProcSeriesTable | INFO - Loading processed series...`
`2022-02-15T03:23:05.500453540Z 2022-02-14 22:23:05,500 | MainThread 140282712611656 | MangaTaggerLib.database.TaskQueueTable | INFO - Loading task queue...`
`2022-02-15T03:23:05.501304773Z 2022-02-14 22:23:05,501 | MainThread 140282712611656 | MangaTaggerLib.database.TaskQueueTable | INFO - Attempting to delete all records in the database...`
`2022-02-15T03:23:05.502076129Z 2022-02-14 22:23:05,501 | MainThread 140282712611656 | MangaTaggerLib.database.TaskQueueTable | INFO - Deletion was successful!`
`2022-02-15T03:23:05.502652765Z 2022-02-14 22:23:05,502 | MainThread 140282712611656 | MangaTaggerLib.MangaTaggerLib | INFO - Starting Manga Tagger - Version 1.2.3-alpha`
`2022-02-15T03:23:05.504401186Z 2022-02-14 22:23:05,504 | MainThread 140282712611656 | MangaTaggerLib.task_queue.QueueWorker | INFO - Watching "/downloads" for new downloads`
`2022-02-15T03:41:10.226251788Z 2022-02-14 22:41:10,226 | Thread-1 140282616253240 | MangaTaggerLib.task_queue.SeriesHandler | INFO - Creation event for "/downloads/Manga/Useless Ponko/Vol. 09 Ch. 064.cbz" will be added to the queue`
`2022-02-15T03:41:10.843578052Z 2022-02-14 22:41:10,842 | MTT-0 140282627644216 | MangaTaggerLib.task_queue.QueueWorker | INFO - Pulling "file created" event from the queue for "/downloads/Manga/Useless Ponko/Vol. 09 Ch. 064.cbz"`
`2022-02-15T03:41:11.846281271Z 2022-02-14 22:41:11,845 | MTT-0 140282627644216 | MangaTaggerLib.MangaTaggerLib | INFO - Now processing "/downloads/Manga/Useless Ponko/Vol. 09 Ch. 064.cbz"...`
`2022-02-15T03:41:11.847161819Z 2022-02-14 22:41:11,846 | MTT-0 140282627644216 | MangaTaggerLib.MangaTaggerLib | INFO - Attempting to rename "Vol. 09 Ch. 064.cbz"...`
`2022-02-15T03:41:11.848214204Z 2022-02-14 22:41:11,847 | MTT-0 140282627644216 | MangaTaggerLib.MangaTaggerLib | ERROR - Unable to parse filename "Vol. 09 Ch. 064.cbz" due to delimiter "-.-" missing`
`2022-02-15T03:41:11.848251194Z Traceback (most recent call last):`
`2022-02-15T03:41:11.848262711Z   File "/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 85, in filename_parser`
`2022-02-15T03:41:11.848273198Z     raise UnparsableFilenameError(filename, '-.-')`
`2022-02-15T03:41:11.848282954Z MangaTaggerLib.errors.UnparsableFilenameError: Unable to parse filename "Vol. 09 Ch. 064.cbz" due to delimiter "-.-" missing`
`2022-02-15T03:41:11.849294834Z 2022-02-14 22:41:11,848 | MTT-0 140282627644216 | MangaTaggerLib.task_queue.QueueWorker | ERROR - 'NoneType' object is not subscriptable` 
`2022-02-15T03:41:11.849329531Z Traceback (most recent call last):`
`2022-02-15T03:41:11.849340271Z   File "/app/Manga-Tagger/MangaTaggerLib/task_queue.py", line 188, in process`
`2022-02-15T03:41:11.849350484Z     MangaTaggerLib.process_manga_chapter(path, uuid.uuid1())`
`2022-02-15T03:41:11.849359927Z   File "/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 68, in process_manga_chapter`
`2022-02-15T03:41:11.849369946Z     metadata_tagger(file_path, manga_details[0], manga_details[1], manga_details[2], logging_info)`
`2022-02-15T03:41:11.849379756Z TypeError: 'NoneType' object is not subscriptable`
`2022-02-15T03:41:11.850084443Z 2022-02-14 22:41:11,849 | MTT-0 140282627644216 | MangaTaggerLib.task_queue.QueueWorker | WARNING - Manga Tagger is unfamiliar with this error. Please log an issue for investigation.`

I am running the FMD2 docker with default filenaming properties. It seems FMD2 succeeds in pulling the file from Mangadex, and Mangatagger can see the file, but it can't do anything with it. Any clues on this?

**Comment by Banh-Canh** [comment]
Hello, it's because fmd2 isn't renaming correctly the files it downloads. It should have been auto-configured (i'll take a look) but if it isn't you have to change fmd2 settings so it output files with a name like:  "%MANGA% -.- %CHAPTER%.cbz"
Manga-Tagger needs this delimiter to parse the filename and recognize the manga/chapter.

**Comment by jje0008** [comment]
Thank you! I went to Options/"Save to" in FMD2 and under the box "Filename:" changed the value to 
`MANGA% -.- %CHAPTER%.%FILENAME%`

Mangatagger succeeded after this change.
