### ISSUE TITLE
[Question] Writing not found manga to json file

### ISSUE THREAD

**Issue by ThePromidius** [Banh-Canh/Manga-Tagger#24]
It's me again. I'm developing a tool to manage manga. Modify metadata, covers etc.
I'd like to make an extension to easily add exceptions to `exceptions.json`

The idea is that when there's a manga not found in the anilist api the info of it would go to `notFound.json` in the data folder. And the extension would read this file to make the action of modifying the file and adding entries to it faster.

The thing is i don't really know how I'd make this thread-safe to say it in some way.
I'd like to know your opinion on this.

**Comment by Banh-Canh** [comment]
Interesting! I'm not sure but I would start from this part: 
[https://github.com/Banh-Canh/Manga-Tagger/blob/48c2175f69282021bf8e78a097aab79667d9c9d8/MangaTaggerLib/MangaTaggerLib.py#L329](url)
and add the relevant code to read/parse the notFound.json and add entry to it.

MT is going to phone anilist api each time before it reads the file though. You could add a check to not call anilist api if there is an entry of the manga in the notFound.json.

**Comment by ThePromidius** [comment]
> MT is going to phone anilist api each time before it reads the file though. You could add a check to not call anilist api if there is an entry of the manga in the notFound.json.

That's not an issue really. If the manga is not listed in the api or there are no synonyms that match. 
The idea is to just make an easy interface its not going to be complicated. I'll investigate on how to safely write to json from threads.
Also let me know if you'd like me to communicate through other methods. Github issues might not be ideal i guess

**Comment by Banh-Canh** [comment]
You are welcome to reach me on discord VictorTK#1380 if you want :)
