### ISSUE TITLE
Readcomics does not download correctly

### ISSUE THREAD

**Issue by shedman214** [Banh-Canh/Manga-Tagger#25]
**OS**: What operating system are you running Manga Tagger on?
I'm running on unraid
**Manga Tagger Version:** What version of Manga Tagger are you running?
v2.0.31.0
**Description of the issue:** Give a clear and concise description of what the issue is.
When I use Readcomics online I get an error and it does not complete. Is there another step to get the comics to download? Manga downloads fine but comics do not. 
**Manga Series:** What manga series (singular or plural) were being tagged when the issue was encountered?

**Screenshots (If applicable):** Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/32603273/173962098-8aca8efa-f596-4ecf-89df-e04cb1ca4359.png)

**Log File**: Please make sure JSON logging is enabled and upload the JSON log file.

**Comment by ThePromidius** [comment]
This should go to https://github.com/Banh-Canh/docker-FMD2
Make sure they are not already downloaded i sometimes have a similar issue randomly.
