### ISSUE TITLE
[BUG] All processed files have the same cover art.

### ISSUE THREAD

**Issue by Matt-Laker** [Banh-Canh/Manga-Tagger#26]
**OS**: What operating system are you running Manga Tagger on?
Ubuntu Server 20.04
**Manga Tagger Version:** What version of Manga Tagger are you running?
Latest from Docker
**Description of the issue:** Give a a clear and concise description of what the issue is.
The system works, but if I put chapters 1-10 in downloads. The output has set all covers to chapter 1. All files are named correctly I.e “Sun-Ken Rock -.- Chapter 1
**Manga Series:** What manga series (singular or plural) were being tagged when the issue was encountered?
Sun-Ken Rock
**Screenshots (If applicable):** Add screenshots to help explain your problem.
N/A
**Log File**: Please make sure JSON logging is enabled and upload the JSON log file.
Nothing in logs shows any form of error

**Comment by ThePromidius** [comment]
set `MANGA_TAGGER_IMAGE_COVER` to `false` in the docker-compose

**Comment by Banh-Canh** [comment]
It's working as intended. MT is pulling the cover art from Anilist and there often is only the cover for the first volume. 
All chapters will use this cover image.
