### ISSUE TITLE
[BUG] 'APIException' is not defined

### ISSUE THREAD

**Issue by KochFolie** [Banh-Canh/Manga-Tagger#27]
I see an error in the log when Manga Tagger tries to call the api:

> 2022-07-22 15:40:16,255 | MTT-0 139965593357112 | MangaTaggerLib.task_queue.QueueWorker | ERROR - name 'APIException' is not defined
Traceback (most recent call last):
  File "/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 317, in metadata_tagger
    manga_search = AniList.search_for_manga_title_by_manga_title(manga_title, format, logging_info)
  File "/app/Manga-Tagger/MangaTaggerLib/api.py", line 50, in search_for_manga_title_by_manga_title
    return cls._post(query, variables, logging_info)
  File "/app/Manga-Tagger/MangaTaggerLib/api.py", line 28, in _post
    return response.json()['data']['Media']
TypeError: 'NoneType' object is not subscriptable
  During handling of the above exception, another exception occurred:
  Traceback (most recent call last):
  File "/app/Manga-Tagger/MangaTaggerLib/task_queue.py", line 188, in process
    MangaTaggerLib.process_manga_chapter(path, uuid.uuid1())
  File "/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 68, in process_manga_chapter
    metadata_tagger(file_path, manga_details[0], manga_details[1], manga_details[2], logging_info, manga_details[3])
  File "/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 318, in metadata_tagger
    except (APIException, ConnectionError) as e:
NameError: name 'APIException' is not defined

I can provide a full log if needed, but I think this should be enough.

**Comment by ThePromidius** [comment]
Never had this exception but there's indeed an import missing for the subsequent exception

 What is the anilist id of the manga that throws this error? 
Does this happen always?

**Comment by ThePromidius** [comment]
Took a further look and this exception handling `File "/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 318, in metadata_tagger
except (APIException, ConnectionError) as e:`
is not required at all. APIException is no longer raised since this fork does not have jikan at all.
And ConnectionError won't be raised either because in the post method its already excepted.

**Comment by KochFolie** [comment]
Thanks for looking into this. The anilist id is rather fitting. It's "404". :)

It does not happen always. Might really be a rate limit, as the log warning (that's never shown, because of the missing APIException type) suggests. 

According to the docs, there is a rate limit of 90 per minute. I might have hit that, since I've tried tagging a lot of files at once: https://anilist.gitbook.io/anilist-apiv2-docs/overview/rate-limiting

So I suggest keeping the try catch and thread.sleep(60) in the code and just replace "APIException" with "Exception". Or maybe detect the header (see docs) and implement some more complicated rate limit handling.

**Comment by ThePromidius** [comment]
As I said earlier thst rate limit applied only when jikan was used (original manga-tagher by inpachi) so there's no point in keeping that code in there it won't be used even if you change it to `Exception`

Ill take a look at their api and see if i can except any rate limit in the proper place which is in the AniList class

**Comment by ThePromidius** [comment]
6d6a2bec82f8d012b0a9e4b80fe7e1420691fd70
Not really sure i like this approach at all but theoretically this should do?
