### ISSUE TITLE
[BUG] Manga not detected when EPUB instead of CBZ

### ISSUE THREAD

**Issue by hvmzx** [Banh-Canh/Manga-Tagger#35]
**OS**: Docker

**Manga Tagger Version:** Latest and Nightly

**Description of the issue:** Downloaded chapters with FMD2 with correct naming but do not get detected

**Manga Series:** Naruto, One Piece, My Hero Academia

**Screenshots (If applicable):** Stuck on this 

`{"threadName": "MainThread", "thread": 140399979608904, "asctime": "2023-01-16 22:10:53,536", "name": "MangaTaggerLib.database.Database", "levelname": "INFO", "message": "Establishing database connection..."}
{"threadName": "MainThread", "thread": 140399979608904, "asctime": "2023-01-16 22:10:53,540", "name": "MangaTaggerLib.database.Database", "levelname": "INFO", "message": "Database connection established!"}
{"threadName": "MainThread", "thread": 140399979608904, "asctime": "2023-01-16 22:10:53,542", "name": "MangaTaggerLib.utils.AppSettings", "levelname": "INFO", "message": "Download directory has been set as \"/downloads\""}
{"threadName": "MainThread", "thread": 140399979608904, "asctime": "2023-01-16 22:10:53,545", "name": "MangaTaggerLib.database.ProcSeriesTable", "levelname": "INFO", "message": "Loading processed series..."}
{"threadName": "MainThread", "thread": 140399979608904, "asctime": "2023-01-16 22:10:53,574", "name": "MangaTaggerLib.database.TaskQueueTable", "levelname": "INFO", "message": "Loading task queue..."}
{"threadName": "MainThread", "thread": 140399979608904, "asctime": "2023-01-16 22:10:53,575", "name": "MangaTaggerLib.database.TaskQueueTable", "levelname": "INFO", "message": "Attempting to delete all records in the database..."}
{"threadName": "MainThread", "thread": 140399979608904, "asctime": "2023-01-16 22:10:53,577", "name": "MangaTaggerLib.database.TaskQueueTable", "levelname": "INFO", "message": "Deletion was successful!"}
{"threadName": "MainThread", "thread": 140399979608904, "asctime": "2023-01-16 22:10:53,581", "name": "MangaTaggerLib.MangaTaggerLib", "levelname": "INFO", "message": "Starting Manga Tagger - Version 1.2.3-alpha"}
{"threadName": "MainThread", "thread": 140399979608904, "asctime": "2023-01-16 22:10:53,589", "name": "MangaTaggerLib.task_queue.QueueWorker", "levelname": "INFO", "message": "Watching \"/downloads\" for new downloads"}
`

**Comment by ThePromidius** [comment]
This is expected.

Epub files have completely different metadata and are not supported by manga-tagger.

If the contents of the epub are images its recommended to convert to cbz and later add a comicinfo.xml in it.

**Comment by hvmzx** [comment]
> This is expected.
> 
> Epub files have completely different metadata and are not supported by manga-tagger.
> 
> If the contents of the epub are images its recommended to convert to cbz and later add a comicinfo.xml in it.
> 

Oh ok i see now, and do you know if by converting my cbz file to epub i can keep the metadata? I need epub for compatibility with my e reader.

Btw, an app merging fmd2 and manga tagger (and manager) with a nice web ui running natively on docker would really be nice.

**Comment by ThePromidius** [comment]
That's highly unlikely due ti the nature of both software.
They are too different.

I plan to add some web interface to manage the database to easily remove entries that you want to redownload for example otherwise it rejects new files as duplicated.

But fmd and manga-tagger will never be combined 
I want to try to make a linux build to allow it barebone 
(Without wine) but that will take a lot of time

**Comment by hvmzx** [comment]
> That's highly unlikely due ti the nature of both software.
> They are too different.
> 
> I plan to add some web interface to manage the database to easily remove entries that you want to redownload for example otherwise it rejects new files as duplicated.
> 
> But fmd and manga-tagger will never be combined 
> I want to try to make a linux build to allow it barebone 
> (Without wine) but that will take a lot of time

At least a linux version of fmd2 would greatly help, the wine part is heavy and clunky

**Comment by ThePromidius** [comment]
Agreed.
I'll close the issue as it's working as expected

**Comment by hvmzx** [comment]
For people that may have the same issue as me : 

- Download with the correct name through FMD2 in CBZ format
- Meta Tagger will pick it up and add the .xml metadata in the cbz file
- Convert to epub using kcc https://github.com/ciromattia/kcc/wiki/ComicRack-metadata

KCC converts to .epub while applying the metadata of the xml from the cbz
